export const weeklyGymPrograms = [
  {
    level: "beginner",
    day: "Monday",
    workout: [
      {
        exercise: "Bodyweight Squats",
        description: "Strengthen your legs and glutes.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Push-Ups",
        description: "Work on chest, shoulders, and triceps.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Plank",
        description: "Build core stability.",
        sets: 3,
        reps: "20 seconds",
      },
      {
        exercise: "Lunges",
        description: "Improve balance and strengthen legs.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Dumbbell Rows",
        description: "Strengthen your back and arms.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Jumping Jacks",
        description: "Light cardio to warm up.",
        sets: 3,
        reps: 20,
      },
      {
        exercise: "Seated Shoulder Press",
        description: "Strengthen shoulders with light dumbbells.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Bicep Curls",
        description: "Focus on arm strength.",
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    level: "beginner",
    day: "Wednesday",
    workout: [
      {
        exercise: "Deadlifts",
        description: "Work on hamstrings and lower back.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Incline Push-Ups",
        description: "Easier version of push-ups for beginners.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Step-Ups",
        description: "Strengthen legs with step exercises.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Crunches",
        description: "Strengthen your abs.",
        sets: 3,
        reps: 15,
      },
      {
        exercise: "Side Plank",
        description: "Focus on obliques.",
        sets: 3,
        reps: "15 seconds per side",
      },
      {
        exercise: "Jump Rope",
        description: "Improve coordination and cardio.",
        sets: 3,
        reps: "30 seconds",
      },
      {
        exercise: "Dumbbell Fly",
        description: "Chest isolation with light dumbbells.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Calf Raises",
        description: "Focus on calf muscles.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    level: "beginner",
    day: "Friday",
    workout: [
      {
        exercise: "Goblet Squats",
        description: "Weighted squats for leg strength.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Push-Ups with Knee Support",
        description: "Modified push-ups for better form.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Plank with Arm Lift",
        description: "Engage your core and shoulders.",
        sets: 3,
        reps: "10 reps per arm",
      },
      {
        exercise: "Mountain Climbers",
        description: "Full-body cardio workout.",
        sets: 3,
        reps: 20,
      },
      {
        exercise: "Bent-Over Dumbbell Rows",
        description: "Target your back muscles.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Tricep Dips",
        description: "Strengthen triceps using a chair.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Leg Raises",
        description: "Focus on lower abdominal muscles.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Russian Twists",
        description: "Work on obliques and core.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    level: "beginner",
    day: "Saturday",
    workout: [
      {
        exercise: "Jump Squats",
        description: "Build explosive leg power.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Wall Sit",
        description: "Strengthen legs and endurance.",
        sets: 3,
        reps: "20 seconds",
      },
      {
        exercise: "Superman Hold",
        description: "Focus on lower back muscles.",
        sets: 3,
        reps: "20 seconds",
      },
      {
        exercise: "Side Lunges",
        description: "Target inner thighs and glutes.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Push-Ups to Downward Dog",
        description: "Combine strength and flexibility.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "High Knees",
        description: "Cardio for endurance.",
        sets: 3,
        reps: "20 seconds",
      },
      {
        exercise: "Dumbbell Deadlifts",
        description: "Work on hamstrings and lower back.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Plank with Hip Dips",
        description: "Engage obliques and core.",
        sets: 3,
        reps: "10 dips",
      },
    ],
  },
  {
    level: "intermediate",
    day: "Monday",
    workout: [
      {
        exercise: "Barbell Squats",
        description: "Heavy squats for leg strength.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Flat Bench Press",
        description: "Chest and triceps workout.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Pull-Ups",
        description: "Strengthen your back and arms.",
        sets: 4,
        reps: 6,
      },
      {
        exercise: "Lunges with Dumbbells",
        description: "Weighted lunges for balance and strength.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Deadlifts",
        description: "Full-body strength exercise.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Plank with Shoulder Taps",
        description: "Core and stability focus.",
        sets: 3,
        reps: "10 taps per side",
      },
      {
        exercise: "Incline Dumbbell Press",
        description: "Focus on upper chest.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Dumbbell Side Lateral Raises",
        description: "Strengthen shoulder muscles.",
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    level: "intermediate",
    day: "Wednesday",
    workout: [
      {
        exercise: "Romanian Deadlifts",
        description: "Hamstring and glute focus.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Weighted Dips",
        description: "Chest and tricep focus.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Seated Cable Rows",
        description: "Strengthen your back.",
        sets: 4,
        reps: 10,
      },
      {
        exercise: "Bulgarian Split Squats",
        description: "Improve balance and leg strength.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Hanging Leg Raises",
        description: "Work on core strength.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Face Pulls",
        description: "Target rear delts and traps.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Overhead Barbell Press",
        description: "Strengthen shoulders and upper body.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Dumbbell Shrugs",
        description: "Target traps and neck.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    level: "intermediate",
    day: "Friday",
    workout: [
      {
        exercise: "Front Squats",
        description: "Emphasize quads and core.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Incline Bench Press",
        description: "Focus on upper chest.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Barbell Rows",
        description: "Strengthen your back.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Step-Ups with Dumbbells",
        description: "Leg and glute focus.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Cable Tricep Pushdowns",
        description: "Isolate tricep muscles.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Hanging Knee Raises",
        description: "Core strength and control.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Arnold Press",
        description: "Shoulder and arm engagement.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Calf Press on Leg Press Machine",
        description: "Isolate calf muscles.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    level: "intermediate",
    day: "Saturday",
    workout: [
      {
        exercise: "Sumo Deadlifts",
        description: "Wide-stance deadlifts for glutes and hamstrings.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Decline Bench Press",
        description: "Lower chest focus.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Lat Pulldowns",
        description: "Strengthen your lats and upper back.",
        sets: 4,
        reps: 10,
      },
      {
        exercise: "Walking Lunges",
        description: "Improve coordination and leg strength.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Russian Twists with Medicine Ball",
        description: "Engage obliques and core.",
        sets: 3,
        reps: 20,
      },
      {
        exercise: "Cable Lateral Raises",
        description: "Shoulder isolation.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Bent-Over Rear Delt Fly",
        description: "Target rear deltoids.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Seated Calf Raises",
        description: "Focus on calf endurance.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    level: "advanced",
    day: "Monday",
    workout: [
      {
        exercise: "Barbell Back Squats",
        description: "Heavy squats for maximum strength.",
        sets: 5,
        reps: 6,
      },
      {
        exercise: "Flat Bench Press",
        description: "Build chest strength with heavy weights.",
        sets: 5,
        reps: 6,
      },
      {
        exercise: "Weighted Pull-Ups",
        description: "Increase back and arm strength.",
        sets: 4,
        reps: 6,
      },
      {
        exercise: "Walking Lunges with Barbell",
        description: "Challenge your legs and balance.",
        sets: 4,
        reps: 12,
      },
      {
        exercise: "Deadlifts",
        description: "Full-body compound exercise.",
        sets: 5,
        reps: 5,
      },
      {
        exercise: "Plank to Push-Up",
        description: "Engage core and upper body.",
        sets: 4,
        reps: "10 reps",
      },
      {
        exercise: "Incline Dumbbell Bench Press",
        description: "Focus on upper chest.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Face Pulls with Rope",
        description: "Rear deltoids and upper traps.",
        sets: 4,
        reps: 12,
      },
    ],
  },
  {
    level: "advanced",
    day: "Wednesday",
    workout: [
      {
        exercise: "Romanian Deadlifts with Barbell",
        description: "Hamstring and glute development.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Weighted Dips",
        description: "Advanced chest and triceps workout.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "T-Bar Rows",
        description: "Strengthen middle back.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Bulgarian Split Squats with Dumbbells",
        description: "Unilateral leg strength focus.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Hanging Toes-to-Bar",
        description: "Advanced core and flexibility exercise.",
        sets: 4,
        reps: 12,
      },
      {
        exercise: "Cable Rope Face Pulls",
        description: "Target rear delts and traps.",
        sets: 4,
        reps: 12,
      },
      {
        exercise: "Overhead Barbell Press",
        description: "Build shoulder and core stability.",
        sets: 4,
        reps: 6,
      },
      {
        exercise: "Barbell Shrugs",
        description: "Heavy trap engagement.",
        sets: 4,
        reps: 15,
      },
    ],
  },
  {
    level: "advanced",
    day: "Friday",
    workout: [
      {
        exercise: "Front Squats",
        description: "Strengthen quads and core under heavy load.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Incline Barbell Bench Press",
        description: "Focus on upper chest strength.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Barbell Rows",
        description: "Heavy back workout.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Step-Ups with Weighted Barbell",
        description: "Target legs and glutes.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Tricep Skull Crushers",
        description: "Focus on tricep growth.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Ab Wheel Rollouts",
        description: "Advanced core exercise.",
        sets: 4,
        reps: 10,
      },
      {
        exercise: "Dumbbell Arnold Press",
        description: "Shoulders and stability.",
        sets: 3,
        reps: 10,
      },
      {
        exercise: "Standing Calf Raises with Barbell",
        description: "Maximum calf strength.",
        sets: 3,
        reps: 20,
      },
    ],
  },
  {
    level: "advanced",
    day: "Saturday",
    workout: [
      {
        exercise: "Deficit Deadlifts",
        description: "Increase range of motion and strength.",
        sets: 5,
        reps: 5,
      },
      {
        exercise: "Incline Dumbbell Fly",
        description: "Stretch and strengthen chest.",
        sets: 4,
        reps: 10,
      },
      {
        exercise: "Weighted Pull-Ups with Chains",
        description: "Advanced back workout.",
        sets: 4,
        reps: 6,
      },
      {
        exercise: "Walking Barbell Lunges",
        description: "Intensify leg and core workout.",
        sets: 4,
        reps: 12,
      },
      {
        exercise: "Medicine Ball Slams",
        description: "Engage core and explosiveness.",
        sets: 4,
        reps: 15,
      },
      {
        exercise: "Cable Lateral Raises",
        description: "Shoulder isolation for advanced lifters.",
        sets: 3,
        reps: 12,
      },
      {
        exercise: "Bent-Over Barbell Rows",
        description: "Mid-back strength.",
        sets: 4,
        reps: 8,
      },
      {
        exercise: "Seated Calf Raises with Heavy Weights",
        description: "Advanced calf endurance and strength.",
        sets: 3,
        reps: 20,
      },
    ],
  },
];

export const muscleGroups = [
  {
    muscle: "Chest",
    exercises: [
      {
        name: "Bench Press",
        description: "Barbell press for overall chest development.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Incline Dumbbell Press",
        description: "Focuses on the upper chest.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Cable Fly",
        description: "Isolation exercise for the chest.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Push-Ups",
        description: "Bodyweight exercise for chest and shoulders.",
        sets: 3,
        reps: 15,
      },
      {
        name: "Decline Bench Press",
        description: "Targets the lower chest.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Dumbbell Pullovers",
        description: "Expands the chest and strengthens lats.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Pec Deck Machine",
        description: "Great for isolating chest muscles.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Incline Push-Ups",
        description: "Targets upper chest using bodyweight.",
        sets: 3,
        reps: 15,
      },
      {
        name: "Chest Dips",
        description: "Focus on lower chest and triceps.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Svend Press",
        description: "Chest activation with lightweight.",
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    muscle: "Back",
    exercises: [
      {
        name: "Pull-Ups",
        description: "Strengthen upper back and biceps.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Deadlifts",
        description: "Full-body exercise targeting the back.",
        sets: 4,
        reps: 6,
      },
      {
        name: "Barbell Rows",
        description: "Strengthen mid-back muscles.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Lat Pulldowns",
        description: "Target lats with a cable machine.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Seated Cable Rows",
        description: "Focus on mid and upper back.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Single-Arm Dumbbell Row",
        description: "Isolate one side of the back.",
        sets: 3,
        reps: 10,
      },
      {
        name: "T-Bar Rows",
        description: "Build thickness in the back.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Face Pulls",
        description: "Strengthen rear delts and upper back.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Hyperextensions",
        description: "Lower back focus.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Shrugs",
        description: "Target traps for upper back.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    muscle: "Legs",
    exercises: [
      {
        name: "Barbell Squats",
        description: "Build strength and size in legs.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Leg Press",
        description: "Focus on quads and hamstrings.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Walking Lunges",
        description: "Improve balance and strengthen legs.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Romanian Deadlifts",
        description: "Target hamstrings and glutes.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Leg Curls",
        description: "Isolate the hamstrings.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Step-Ups",
        description: "Build single-leg strength.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Calf Raises",
        description: "Strengthen calf muscles.",
        sets: 3,
        reps: 15,
      },
      {
        name: "Goblet Squats",
        description: "Great for beginners and quad focus.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Bulgarian Split Squats",
        description: "Target quads, hamstrings, and glutes.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Box Jumps",
        description: "Plyometric exercise for explosive strength.",
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    muscle: "Biceps",
    exercises: [
      {
        name: "Barbell Curls",
        description: "Standard curl for biceps growth.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Hammer Curls",
        description: "Focus on brachialis and forearms.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Preacher Curls",
        description: "Isolate biceps for better muscle engagement.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Concentration Curls",
        description: "Focus on peak contraction.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Incline Dumbbell Curls",
        description: "Stretch the biceps for fuller development.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Cable Curls",
        description: "Isolation curl using a cable machine.",
        sets: 3,
        reps: 12,
      },
    ],
  },
  {
    muscle: "Triceps",
    exercises: [
      {
        name: "Tricep Dips",
        description: "Focus on triceps and chest.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Close-Grip Bench Press",
        description: "Targets triceps while working chest.",
        sets: 4,
        reps: 8,
      },
      {
        name: "Overhead Tricep Extension",
        description: "Focus on long head of the triceps.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Tricep Pushdowns",
        description: "Isolation exercise using cable machine.",
        sets: 4,
        reps: 10,
      },
      {
        name: "Skull Crushers",
        description: "Target triceps with an EZ bar.",
        sets: 3,
        reps: 10,
      },
      {
        name: "Diamond Push-Ups",
        description: "Bodyweight exercise for triceps and chest.",
        sets: 3,
        reps: 15,
      },
    ],
  },
  {
    muscle: "Core",
    exercises: [
      {
        name: "Planks",
        description: "Static hold to strengthen the entire core.",
        sets: 3,
        reps: "30 seconds",
      },
      {
        name: "Russian Twists",
        description: "Work the obliques with a twisting motion.",
        sets: 3,
        reps: 20,
      },
      {
        name: "Leg Raises",
        description: "Target lower abs.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Bicycle Crunches",
        description: "Effective for upper and lower abs.",
        sets: 3,
        reps: 20,
      },
      {
        name: "Mountain Climbers",
        description: "Engage core with a cardio movement.",
        sets: 3,
        reps: 20,
      },
      {
        name: "Hanging Leg Raises",
        description: "Target the lower abs and hip flexors.",
        sets: 3,
        reps: 12,
      },
      {
        name: "Ab Rollouts",
        description: "Use an ab wheel to roll out and engage your core.",
        sets: 3,
        reps: 12,
      },
    ],
  },
];
export const gymRecipes = [
  // Weight Loss Recipes
  {
    type: "weightLoss",
    name: "Grilled Chicken Salad with Avocado",
    description: "A low-calorie, high-protein salad to help with fat loss.",
    ingredients: [
      "150g grilled chicken breast",
      "1/2 avocado, sliced",
      "Mixed greens",
      "1 tablespoon olive oil",
      "1 tablespoon balsamic vinegar",
    ],
    instructions:
      "Grill chicken, mix with greens and avocado, drizzle with oil and vinegar.",
  },
  {
    type: "weightLoss",
    name: "Egg White Scramble with Spinach and Mushrooms",
    description:
      "A protein-packed, low-calorie breakfast perfect for weight loss.",
    ingredients: [
      "4 egg whites",
      "1/2 cup spinach",
      "1/4 cup mushrooms",
      "1 teaspoon olive oil",
    ],
    instructions:
      "Sauté spinach and mushrooms, add egg whites, cook until set.",
  },
  {
    type: "weightLoss",
    name: "Zucchini Noodles with Pesto Chicken",
    description: "A low-carb meal with vegetables and lean protein.",
    ingredients: [
      "1 zucchini",
      "150g grilled chicken",
      "2 tablespoons pesto",
      "Cherry tomatoes",
    ],
    instructions:
      "Sauté zucchini noodles, toss with pesto, top with chicken and tomatoes.",
  },
  {
    type: "weightLoss",
    name: "Greek Yogurt with Berries",
    description: "A healthy snack with probiotics and antioxidants.",
    ingredients: [
      "1/2 cup Greek yogurt",
      "1/4 cup mixed berries",
      "1 teaspoon chia seeds",
    ],
    instructions: "Mix yogurt with berries and top with chia seeds.",
  },
  {
    type: "weightLoss",
    name: "Salmon with Asparagus",
    description: "A lean, high-protein meal with healthy fats.",
    ingredients: [
      "200g salmon",
      "1 bunch asparagus",
      "1 tablespoon olive oil",
      "Lemon wedges",
    ],
    instructions: "Grill salmon, roast asparagus, and serve with lemon.",
  },
  {
    type: "weightLoss",
    name: "Cucumber and Tomato Salad",
    description: "Refreshing salad with minimal calories.",
    ingredients: [
      "1 cucumber",
      "2 tomatoes",
      "1 tablespoon olive oil",
      "1 tablespoon balsamic vinegar",
    ],
    instructions: "Chop vegetables, mix with oil and vinegar.",
  },
  {
    type: "weightLoss",
    name: "Chicken Lettuce Wraps",
    description: "Healthy, low-carb wraps with lean protein.",
    ingredients: [
      "150g ground chicken",
      "Lettuce leaves",
      "1/4 cup diced onions",
      "Soy sauce",
    ],
    instructions: "Cook chicken, season with soy sauce, wrap in lettuce.",
  },
  {
    type: "weightLoss",
    name: "Sweet Potato Fries",
    description: "Low-calorie, nutritious fries.",
    ingredients: [
      "1 sweet potato",
      "1 tablespoon olive oil",
      "Salt and pepper",
    ],
    instructions:
      "Cut sweet potato into fries, roast with olive oil and seasonings.",
  },
  {
    type: "weightLoss",
    name: "Zucchini Chips",
    description: "Healthy, low-calorie snack alternative to chips.",
    ingredients: ["1 zucchini", "1 tablespoon olive oil", "Sea salt"],
    instructions: "Slice zucchini, toss in olive oil, and bake until crispy.",
  },
  {
    type: "weightLoss",
    name: "Spicy Tuna Salad",
    description: "A flavorful, low-carb dish for weight loss.",
    ingredients: [
      "1 can tuna",
      "1 tablespoon Greek yogurt",
      "1 teaspoon hot sauce",
      "Diced celery",
    ],
    instructions: "Mix tuna, yogurt, hot sauce, and celery until combined.",
  },

  // Weight Gain Recipes
  {
    type: "weightGain",
    name: "Protein-Packed Smoothie",
    description: "A calorie-dense smoothie to help increase weight.",
    ingredients: [
      "1 banana",
      "1 scoop protein powder",
      "1 tablespoon peanut butter",
      "1/2 cup whole milk",
    ],
    instructions: "Blend all ingredients until smooth.",
  },
  {
    type: "weightGain",
    name: "Chicken and Quinoa Bowl",
    description: "A high-protein, high-calorie meal.",
    ingredients: [
      "150g grilled chicken",
      "1/2 cup cooked quinoa",
      "1/2 avocado",
      "1 tablespoon olive oil",
    ],
    instructions:
      "Combine chicken, quinoa, and avocado, drizzle with olive oil.",
  },
  {
    type: "weightGain",
    name: "Sweet Potato and Black Bean Salad",
    description: "A hearty salad packed with carbs and protein.",
    ingredients: [
      "1 sweet potato",
      "1/2 cup black beans",
      "1/4 cup corn",
      "1 tablespoon olive oil",
    ],
    instructions:
      "Mix roasted sweet potato with beans and corn, drizzle with olive oil.",
  },
  {
    type: "weightGain",
    name: "Egg and Avocado Toast",
    description: "A quick and easy calorie-dense meal.",
    ingredients: ["2 slices whole grain bread", "2 eggs", "1/2 avocado"],
    instructions: "Toast bread, fry eggs, and mash avocado on toast.",
  },
  {
    type: "weightGain",
    name: "Peanut Butter Banana Oatmeal",
    description: "High-calorie breakfast with healthy fats.",
    ingredients: [
      "1/2 cup oats",
      "1 banana",
      "2 tablespoons peanut butter",
      "1 cup whole milk",
    ],
    instructions: "Cook oats with milk, top with banana and peanut butter.",
  },
  {
    type: "weightGain",
    name: "Beef and Rice Stir-Fry",
    description: "A protein and carb-packed stir-fry.",
    ingredients: [
      "150g ground beef",
      "1/2 cup cooked rice",
      "1/4 cup peas",
      "1 tablespoon soy sauce",
    ],
    instructions: "Cook beef and vegetables, stir in rice and soy sauce.",
  },
  {
    type: "weightGain",
    name: "Chicken Alfredo Pasta",
    description: "A calorie-dense pasta dish with protein.",
    ingredients: ["150g chicken", "1/2 cup alfredo sauce", "1 cup pasta"],
    instructions: "Cook pasta, top with grilled chicken and alfredo sauce.",
  },
  {
    type: "weightGain",
    name: "Coconut Yogurt Parfait",
    description: "A high-calorie, creamy dessert.",
    ingredients: [
      "1/2 cup coconut yogurt",
      "1/4 cup granola",
      "1 tablespoon honey",
      "Berries",
    ],
    instructions:
      "Layer yogurt with granola, drizzle with honey, top with berries.",
  },
  {
    type: "weightGain",
    name: "Turkey and Cheese Wraps",
    description: "A quick and calorie-dense snack.",
    ingredients: [
      "3 slices turkey",
      "2 slices cheese",
      "1 tortilla wrap",
      "Lettuce",
    ],
    instructions: "Layer turkey, cheese, and lettuce in a wrap, roll it up.",
  },
  {
    type: "weightGain",
    name: "Nut Butter Energy Balls",
    description: "A perfect snack for weight gain.",
    ingredients: [
      "1 cup oats",
      "1/2 cup peanut butter",
      "1/4 cup honey",
      "1/4 cup chocolate chips",
    ],
    instructions:
      "Mix all ingredients, roll into balls, refrigerate until firm.",
  },
];
